name: Test Methor

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout Deno Module
        uses: actions/checkout@v2

      - name: Setting up Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: 1.4.6

      - name: Lint Deno Module
        run: deno fmt --check

      - name: Build Deno Module
        run: deno run --reload main.ts 1+2

      - name: Test Deno Module
        run: deno test --allow-none
